import { StyleSheet } from 'react-native';

export const COLORS = {
  bgDark: '#F1F5F9',        // Light theme background
  surfaceBlue: '#FFFFFF',   // White surfaces/cards
  borderBlue: '#E2E8F0',    // Light borders
  textSecondary: '#475569', // Medium gray text
  textMuted: '#64748B',     // Muted gray text
  accentAmber: '#EA580C',   // Sharp high-contrast orange-amber
  errorRed: '#FEF2F2',      // Alert red background
  errorText: '#DC2626',     // Alert red text
  successGreen: '#16A34A',  // Success/Active label color
  activeGreen: '#22C55E',   // Bright status green
  white: '#FFFFFF',         // White color (for actual white text on dark buttons/badges!)
  lightBlueGrad: '#0F172A', // Navy theme accent
  blackText: '#0F172A',     // Direct black/charcoal text for high contrast light mode headings
};

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bgDark,
  },
  center: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
    backgroundColor: COLORS.bgDark,
  },
  loadingText: {
    color: '#475569',
    marginTop: 16,
    fontSize: 14,
    textAlign: 'center',
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 40,
  },
  headerSpacer: {
    height: 40,
  },
  brandingBox: {
    alignItems: 'center',
    marginBottom: 28,
  },
  badgeShieldIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#E2E8F0',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 2,
    borderColor: COLORS.accentAmber,
  },
  badgeHeroText: {
    fontSize: 38,
  },
  pnpTitle: {
    color: COLORS.blackText,
    fontWeight: 'bold',
    fontSize: 18,
    textAlign: 'center',
    letterSpacing: 1.5,
  },
  pnpSubTitle: {
    color: COLORS.accentAmber,
    fontSize: 10,
    fontWeight: 'bold',
    letterSpacing: 2.2,
    marginTop: 4,
  },
  formCard: {
    backgroundColor: COLORS.surfaceBlue,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.borderBlue,
    padding: 20,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 10,
    elevation: 4,
  },
  cardHeader: {
    color: COLORS.blackText,
    fontSize: 14,
    fontWeight: 'bold',
    letterSpacing: 1,
    marginBottom: 16,
    textAlign: 'center',
  },
  inputLabel: {
    color: '#475569',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.8,
    marginBottom: 6,
    marginTop: 12,
  },
  input: {
    backgroundColor: '#F8FAFC',
    color: COLORS.blackText,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
  },
  gpsErrorBox: {
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FCA5A5',
    padding: 12,
    borderRadius: 8,
    marginTop: 16,
  },
  gpsErrorTitle: {
    color: '#991B1B',
    fontSize: 11,
    fontWeight: 'bold',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  gpsErrorMessage: {
    color: '#991B1B',
    fontSize: 10,
    lineHeight: 14,
  },
  gpsButtonSmall: {
    backgroundColor: '#DC2626',
    borderRadius: 4,
    padding: 8,
    alignItems: 'center',
    marginTop: 10,
  },
  gpsButtonText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 'bold',
  },
  submitBtn: {
    backgroundColor: COLORS.accentAmber,
    paddingVertical: 15,
    borderRadius: 6,
    alignItems: 'center',
    marginTop: 24,
  },
  submitBtnText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 14,
    letterSpacing: 1.2,
  },
  disclaimerContainer: {
    backgroundColor: '#F8FAFC',
    borderLeftWidth: 3,
    borderLeftColor: '#F25C05',
    padding: 14,
    borderRadius: 6,
    marginTop: 24,
  },
  disclaimerHead: {
    color: COLORS.accentAmber,
    fontSize: 10,
    fontWeight: 'bold',
    letterSpacing: 0.8,
    marginBottom: 4,
  },
  disclaimerText: {
    color: '#475569',
    fontSize: 10,
    lineHeight: 14,
  },

  // --- DASHBOARD & NAVBAR ---
  navbar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLORS.surfaceBlue,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderBlue,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  navLeading: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  navShield: {
    fontSize: 24,
    marginRight: 10,
  },
  navTitle: {
    color: COLORS.blackText,
    fontWeight: 'bold',
    fontSize: 14,
  },
  navSub: {
    color: COLORS.accentAmber,
    fontSize: 9,
    fontWeight: 'bold',
  },
  navTabs: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  tab: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 4,
    marginRight: 6,
  },
  tabActive: {
    backgroundColor: '#E2E8F0',
  },
  tabText: {
    color: '#475569',
    fontSize: 12,
    fontWeight: 'bold',
  },
  tabTextActive: {
    color: COLORS.blackText,
  },
  tabExit: {
    backgroundColor: '#DC2626',
    borderRadius: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  tabExitText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  dashboardContainer: {
    padding: 16,
    paddingBottom: 30,
  },
  dangerAlertBar: {
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FCA5A5',
    padding: 10,
    borderRadius: 6,
    marginBottom: 16,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dangerAlertText: {
    color: '#991B1B',
    fontSize: 10,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  dangerSettingsLink: {
    color: '#DC2626',
    fontSize: 10,
    fontWeight: 'bold',
    marginLeft: 6,
  },
  card: {
    backgroundColor: COLORS.surfaceBlue,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.borderBlue,
    padding: 16,
    marginBottom: 16,
  },
  cardHeading: {
    color: COLORS.blackText,
    fontSize: 12,
    fontWeight: 'bold',
    letterSpacing: 1,
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    paddingBottom: 6,
  },
  shiftCard: {
    borderColor: '#CBD5E1',
  },
  shiftCardActive: {
    borderColor: COLORS.successGreen,
  },
  shiftHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  statusPill: {
    backgroundColor: '#E2E8F0',
    color: COLORS.blackText,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 12,
    fontSize: 10,
    fontWeight: 'bold',
  },
  gmtText: {
    color: COLORS.textMuted,
    fontSize: 10,
    fontWeight: '600',
  },
  activeShiftLabel: {
    color: '#475569',
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 0.8,
    marginTop: 14,
  },
  policeDutyPlate: {
    color: COLORS.blackText,
    fontSize: 22,
    fontWeight: '900',
    letterSpacing: 1.5,
    marginVertical: 4,
  },
  shiftDisclaimer: {
    color: '#475569',
    fontSize: 10,
    lineHeight: 14,
    marginBottom: 14,
  },
  toggleShiftBtn: {
    paddingVertical: 14,
    borderRadius: 6,
    alignItems: 'center',
  },
  toggleShiftBtnStart: {
    backgroundColor: COLORS.accentAmber,
  },
  toggleShiftBtnStop: {
    backgroundColor: COLORS.errorText,
  },
  toggleShiftBtnText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 12,
    letterSpacing: 1,
  },
  syncCountsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginVertical: 10,
  },
  countWidget: {
    alignItems: 'center',
    flex: 1,
  },
  countVal: {
    color: COLORS.accentAmber,
    fontSize: 32,
    fontWeight: 'bold',
  },
  countTitle: {
    color: '#475569',
    fontSize: 10,
    letterSpacing: 0.5,
  },
  actionsRow: {
    flexDirection: 'row',
    marginTop: 14,
  },
  actionBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 4,
    alignItems: 'center',
    marginHorizontal: 4,
  },
  primaryActionBtn: {
    backgroundColor: '#1E3A8A',
  },
  secActionBtn: {
    backgroundColor: '#64748B',
  },
  actionBtnText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  emptyTableText: {
    color: COLORS.textMuted,
    fontSize: 11,
    textAlign: 'center',
    marginVertical: 14,
    fontStyle: 'italic',
  },
  logRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    paddingVertical: 10,
  },
  logLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  logTimeSymbol: {
    fontSize: 16,
    marginRight: 10,
  },
  logCoords: {
    color: COLORS.blackText,
    fontSize: 13,
    fontWeight: '600',
  },
  logCapturedText: {
    color: '#64748B',
    fontSize: 10,
    marginTop: 2,
  },
  logRight: {
    alignItems: 'flex-end',
  },
  logSignalText: {
    color: COLORS.accentAmber,
    fontSize: 10,
    fontWeight: 'bold',
  },
  logSpeedText: {
    color: COLORS.blackText,
    fontSize: 12,
    fontWeight: 'bold',
    marginTop: 2,
  },

  // --- SECTOR MAP ELEMENTS ---
  mapReplica: {
    height: 180,
    backgroundColor: '#EDF2F7',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
    marginBottom: 16,
  },
  mapEmoji: {
    fontSize: 40,
    marginBottom: 8,
  },
  mapTitle: {
    color: COLORS.blackText,
    fontWeight: 'bold',
    fontSize: 14,
    letterSpacing: 1,
  },
  mapSub: {
    color: '#475569',
    fontSize: 11,
    textAlign: 'center',
    marginTop: 4,
  },
  mapLine: {
    height: 2,
    backgroundColor: COLORS.accentAmber,
    width: '40%',
    marginVertical: 10,
  },
  mapIndicator: {
    color: COLORS.accentAmber,
    fontSize: 8,
    fontWeight: 'condensed',
    letterSpacing: 0.5,
  },
  scheduleDetailBox: {
    backgroundColor: '#F8FAFC',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: COLORS.borderBlue,
    padding: 14,
    marginTop: 8,
  },
  schedTitle: {
    color: COLORS.blackText,
    fontSize: 11,
    fontWeight: 'bold',
    letterSpacing: 0.8,
    marginBottom: 10,
  },
  schedRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  schedKey: {
    color: '#64748B',
    fontSize: 11,
  },
  schedValue: {
    color: COLORS.blackText,
    fontSize: 11,
    fontWeight: 'bold',
  },
  sosCard: {
    borderColor: '#EF4444',
    borderWidth: 2,
    backgroundColor: '#FEF2F2',
    padding: 16,
    borderRadius: 8,
    marginBottom: 16,
    alignItems: 'center',
  },
  sosHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 12,
  },
  sosPill: {
    backgroundColor: '#EF4444',
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: 'bold',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
  },
  sosWarningText: {
    color: '#EF4444',
    fontWeight: 'bold',
    fontSize: 14,
    letterSpacing: 2,
    alignSelf: 'center',
  },
  sosDesc: {
    color: '#7F1D1D',
    fontSize: 11,
    textAlign: 'center',
    marginBottom: 16,
    lineHeight: 16,
  },
  sosTriggerButton: {
    backgroundColor: '#DC2626',
    borderRadius: 50,
    width: 90,
    height: 90,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 4,
    borderColor: '#FCA5A5',
    shadowColor: '#EF4444',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.6,
    shadowRadius: 10,
    elevation: 8,
  },
  sosTriggerText: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 24,
    letterSpacing: 1.5,
  },
  sosTriggerSubText: {
    color: '#FCA5A5',
    fontWeight: 'bold',
    fontSize: 8,
  },
  logRowSos: {
    borderLeftWidth: 4,
    borderLeftColor: '#EF4444',
    backgroundColor: '#FEE2E2',
  },
  logRowSosText: {
    color: '#991B1B',
    fontWeight: 'bold',
  },
  patrolNotificationBar: {
    backgroundColor: '#991B1B', // Red alert background
    borderBottomWidth: 2,
    borderBottomColor: '#F87171',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    paddingHorizontal: 14,
    width: '100%',
  },
  patrolNotificationInfo: {
    flex: 1,
    marginRight: 10,
  },
  patrolNotificationTitle: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 12,
    letterSpacing: 0.5,
  },
  patrolNotificationSub: {
    color: '#FEE2E2',
    fontSize: 9.5,
  },
  patrolNotificationButtonSos: {
    backgroundColor: '#DC2626',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
    elevation: 3,
  },
  patrolNotificationButtonSosText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 13,
    letterSpacing: 1,
  },
});
